[package]
name = "axmacros"
version = "0.1.0"
edition = "2024"
description = "Procedural macros for ArceOS"


[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.95", features = ["span-locations"] }
quote = "1.0.35"
syn = { version = "2.0.48", features = ["full"] }
